<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserEmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 31,
                'name' => 'Employee1 Hyundai',
                'email' => 'Employee1hyundai@korps.com',
                'user_type' => 'employee',
                'employee_id' => 'EMP-00123',
                'profile_pic' => null,
                'player_id' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'remember_token' => 'bW3e4XNywsaZGvClFBhEtidwHmdAhb8IFp3t9zWZzguup3No0NsK4jTsAIcc',
                'created_at' => '2025-10-30 06:23:16',
                'updated_at' => '2025-10-30 06:23:16',
                'reporting_to' => null,
            ],
            [
                'id' => 32,
                'name' => 'Tester',
                'email' => 'tester@gmail.com',
                'user_type' => 'employee',
                'employee_id' => '7856',
                'profile_pic' => 'profile_pics/7856.jpeg',
                'player_id' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'remember_token' => null,
                'created_at' => '2025-10-30 06:51:41',
                'updated_at' => '2025-10-30 13:30:31',
                'reporting_to' => null,
            ],
            [
                'id' => 33,
                'name' => 'Employee2Hyundai',
                'email' => 'Employee2hyundai@korps.com',
                'user_type' => 'employee',
                'employee_id' => 'EMP-00124',
                'profile_pic' => null,
                'player_id' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'remember_token' => null,
                'created_at' => '2025-10-30 06:57:31',
                'updated_at' => '2025-10-30 07:01:48',
                'reporting_to' => null,
            ],
            [
                'id' => 34,
                'name' => 'Employee3hyundai',
                'email' => 'Employee3hyundai@korps.com',
                'user_type' => 'employee',
                'employee_id' => 'EMP-00125',
                'profile_pic' => null,
                'player_id' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'remember_token' => null,
                'created_at' => '2025-10-30 07:10:05',
                'updated_at' => '2025-10-30 07:10:05',
                'reporting_to' => null,
            ],
            [
                'id' => 35,
                'name' => 'test 2',
                'email' => 'test2@gmail.com',
                'user_type' => 'employee',
                'employee_id' => '2222',
                'profile_pic' => 'profile_pics/2222.jpeg',
                'player_id' => null,
                'email_verified_at' => null,
                'password' => Hash::make('password'),
                'remember_token' => null,
                'created_at' => '2025-10-30 10:20:52',
                'updated_at' => '2025-10-30 10:20:52',
                'reporting_to' => null,
            ],
        ]);

        DB::table('employees')->insert([
            [
                'user_id' => 31,
                'name' => 'Employee1 Hyundai',
                'email' => 'Employee1hyundai@korps.com',
                'password' => Hash::make('password'),
                'designation' => 'Sales Executive',
                'department_id' => 1,
                'employee_id' => 'EMP-00123',
                'role_id' => 5,
                'dealership_id' => 1,
                'zone_id' => null,
                'profile_pic' => null,
                'mobile' => '9999999999',
                'gender' => 'Male',
                'joining_date' => '2025-10-29',
                'dob' => '2025-10-29',
                'reporting_to' => null,
                'is_broker' => 0,
                'address' => 'Address',
                'created_at' => '2025-10-30 06:23:16',
                'updated_at' => '2025-10-30 06:23:16',
                'email_verified_at' => null,
                'remember_token' => null,
                'task_id' => null,
                'task_started_time' => null,
                'task_status' => null,
                'is_tracking_on' => 0,
                'country' => null,
            ],
            [
                'user_id' => 32,
                'name' => 'Tester',
                'email' => 'tester@gmail.com',
                'password' => Hash::make('password'),
                'designation' => 'staff',
                'department_id' => 1,
                'employee_id' => '7856',
                'role_id' => 5,
                'dealership_id' => 2,
                'zone_id' => 1,
                'profile_pic' => 'profile_pics/7856.jpeg',
                'mobile' => '8974565252',
                'gender' => 'Male',
                'joining_date' => '2025-10-30',
                'dob' => '2002-03-07',
                'reporting_to' => null,
                'is_broker' => 1,
                'address' => 'rthdrtyrytyutyurtu',
                'created_at' => '2025-10-30 06:51:41',
                'updated_at' => '2025-10-30 13:30:31',
                'email_verified_at' => null,
                'remember_token' => null,
                'task_id' => null,
                'task_started_time' => null,
                'task_status' => null,
                'is_tracking_on' => 0,
                'country' => null,
            ],
            [
                'user_id' => 33,
                'name' => 'Employee2Hyundai',
                'email' => 'Employee2hyundai@korps.com',
                'password' => Hash::make('password'),
                'designation' => 'Service Executive',
                'department_id' => 3,
                'employee_id' => 'EMP-00124',
                'role_id' => 4,
                'dealership_id' => 1,
                'zone_id' => null,
                'profile_pic' => null,
                'mobile' => '111-222-3333',
                'gender' => 'Male',
                'joining_date' => '2025-10-29',
                'dob' => '2025-10-29',
                'reporting_to' => null,
                'is_broker' => 0,
                'address' => 'Address',
                'created_at' => '2025-10-30 06:57:31',
                'updated_at' => '2025-10-30 07:01:48',
                'email_verified_at' => null,
                'remember_token' => null,
                'task_id' => null,
                'task_started_time' => null,
                'task_status' => null,
                'is_tracking_on' => 0,
                'country' => null,
            ],
            [
                'user_id' => 34,
                'name' => 'Employee3hyundai',
                'email' => 'Employee3hyundai@korps.com',
                'password' => Hash::make('password'),
                'designation' => 'Parts Executive',
                'department_id' => 2,
                'employee_id' => 'EMP-00125',
                'role_id' => 5,
                'dealership_id' => 1,
                'zone_id' => null,
                'profile_pic' => null,
                'mobile' => '111-222-3334',
                'gender' => 'Female',
                'joining_date' => '2025-10-29',
                'dob' => '2025-10-29',
                'reporting_to' => null,
                'is_broker' => 0,
                'address' => 'Address',
                'created_at' => '2025-10-30 07:10:05',
                'updated_at' => '2025-10-30 07:10:05',
                'email_verified_at' => null,
                'remember_token' => null,
                'task_id' => null,
                'task_started_time' => null,
                'task_status' => null,
                'is_tracking_on' => 0,
                'country' => null,
            ],
            [
                'user_id' => 35,
                'name' => 'test 2',
                'email' => 'test2@gmail.com',
                'password' => Hash::make('password'),
                'designation' => 'staff',
                'department_id' => 1,
                'employee_id' => '2222',
                'role_id' => 3,
                'dealership_id' => 2,
                'zone_id' => 4,
                'profile_pic' => 'profile_pics/2222.jpeg',
                'mobile' => null,
                'gender' => 'Male',
                'joining_date' => '2025-10-30',
                'dob' => '2006-06-14',
                'reporting_to' => null,
                'is_broker' => 1,
                'address' => 'tyujgjgjghj',
                'created_at' => '2025-10-30 10:20:52',
                'updated_at' => '2025-10-30 10:20:52',
                'email_verified_at' => null,
                'remember_token' => null,
                'task_id' => null,
                'task_started_time' => null,
                'task_status' => null,
                'is_tracking_on' => 0,
                'country' => null,
            ],
        ]);
    }
}
